name: Build & Deploy Storybook
on:
  push:
    branches:
      - master
jobs:
  chromatic-deployment:
    name: Deploy to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
