name: Release

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    name: Publish to GPR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"

      - name: Ensure access
        run: npm whoami --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Config git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Bootstrap lerna
        run: yarn bootstrap

      - name: Bump versions and publish packages
        run: |
          yarn version:ci
          yarn publish:ci
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
